AY1920S1-CS2113T-F14-4/main

config/checkstyle/checkstyle.xml
CheckStyle is in-place prior to porting. Added comment to remind about changing IDE settings.
=> [CS2113T-F14-4]-rssujay-A-CheckStyle

build.gradle, src/main/java/duke/DateTime.java, src/main/java/duke/Duke.java, src/main/java/duke/Storage.java, src/main/java/duke/commands/AddCommand.java, src/main/java/duke/tasks/Deadline.java, src/main/java/duke/tasks/Event.java, src/test/java/DateTimeTest.java
Added library natty in build.gradle.
Changed some classes to accomodate changes.
DateTime now wraps java.util.Date
=> [CS2113T-F14-4]-TCK1997-A-Libraries

src/main/java/duke/DateTime.java, src/main/java/duke/tasks/Task.java, src/test/java/StorageTest.java
1) Modify tests for storage class to sufficiently cover CRUD operations.
2) Change Task to abstract class 
3) Clean up unused imports.
=> Update storage unit tests and maintenance

src/main/java/duke/Parser.java
When the done command is used but has no index, the system crashes. This bug fix will instead output, "Please give an index".
=> fix bug when done has no index

src/main/java/duke/DateTime.java, src/main/java/duke/Parser.java, src/main/java/duke/TaskList.java, src/main/java/duke/Ui.java, src/main/java/duke/commands/ReminderCommand.java, src/main/java/duke/tasks/Deadline.java, src/main/java/duke/tasks/Event.java, src/main/java/duke/tasks/Task.java, src/test/java/ReminderCommandTest.java
1) Fix storage format bug (from dd/MM/yyyy HHmm to  MM/dd/yyyy HH:mm) to prevent natty from reacting unexpectedly upon loading of data from storage on subsequent runs.
2) Fix crash when empty List is passed as argument to showFormatted method of the Ui class.
3) Rename methods for greater accuracy based on return types and make Task an abstract class.
4) Add Reminders functionality accessible through user input "remind"
=> [CS2113T-F14-4]-rssujay-B-Reminders

src/main/java/duke/Parser.java, src/main/java/duke/Storage.java, src/main/java/duke/commands/AddCommand.java, src/main/java/duke/tasks/Within.java, src/test/java/WithinTest.java
1. Added in Within task
2. Added in tests
=> [CS2113T-F14-4]-ttippinyu-B-DoWithinPeriodTasks

src/main/java/duke/Duke.java, src/main/java/duke/Parser.java, src/main/java/duke/Storage.java, src/main/java/duke/commands/Command.java, src/main/java/duke/commands/FileCommand.java, src/main/java/duke/tasks/FileTask.java, src/test/java/DukeTest.java, src/test/java/FileTest.java
Issue #53 and #54
1. Added a isFileCommand into Command class
2. Added a TaskList object and Storage object for files in Duke
3. Created a FileTask class for files which extends from Task
4. Created a FileCommand for different file actions
5. Added file command functionality in parser
=> File Tracking Feature

src/main/java/duke/commands/SnoozeCommand.java, src/main/java/duke/tasks/After.java, src/main/java/duke/tasks/Deadline.java, src/main/java/duke/tasks/Event.java, src/main/java/duke/tasks/FileTask.java, src/main/java/duke/tasks/Fixed.java, src/main/java/duke/tasks/Recurring.java, src/main/java/duke/tasks/Task.java, src/main/java/duke/tasks/Tentative.java, src/main/java/duke/tasks/Todo.java, src/main/java/duke/tasks/Within.java
- Existing reminders command works for #51 
- Methods common to multiple tasks added to abstract class Tasks
- Further refactoring should be done post-architectural decisions
=> Refactor tasks

src/main/java/duke/DateTime.java, src/main/java/duke/Storage.java, src/main/java/duke/commands/AddCommand.java, src/main/java/duke/commands/FindFreeCommand.java, src/main/java/duke/commands/SetCommand.java, src/main/java/duke/commands/ViewScheduleCommand.java, src/main/java/duke/items/tasks/Deadline.java, src/main/java/duke/items/tasks/Event.java, src/main/java/duke/items/tasks/Recurring.java, src/main/java/duke/items/tasks/Task.java, src/main/java/duke/items/tasks/Tentative.java, src/main/java/duke/items/tasks/Within.java, src/test/java/DateTimeTest.java, src/test/java/RecurringTest.java, src/test/java/ReminderCommandTest.java, src/test/java/StorageTest.java, src/test/java/TentativeTest.java, src/test/java/TimeConflictTest.java, src/test/java/ViewScheduleTest.java, src/test/java/WithinTest.java
Encapsulate natty Parser inside of DateTime to change all parsing of
Date Strings to be done inside of DateTime object.
=> Refactor all Date parsing into DateTime

.gitignore, src/main/java/spinbox/Module.java, src/main/java/spinbox/SpinBox.java, src/main/java/spinbox/Storage.java, src/main/java/spinbox/commands/AddCommand.java, src/main/java/spinbox/commands/DeleteCommand.java, src/main/java/spinbox/commands/DoneCommand.java, src/main/java/spinbox/commands/FileCommand.java, src/main/java/spinbox/commands/MultipleCommand.java, src/main/java/spinbox/commands/SetCommand.java, src/main/java/spinbox/exceptions/CorruptedDataException.java, src/main/java/spinbox/exceptions/FileCreationException.java, src/main/java/spinbox/exceptions/StorageException.java, src/main/java/spinbox/items/File.java, src/main/java/spinbox/items/GradedComponent.java, src/main/java/spinbox/items/Item.java, src/main/java/spinbox/lists/FileList.java, src/main/java/spinbox/lists/GradeList.java, src/main/java/spinbox/lists/ModuleContainer.java, src/main/java/spinbox/lists/SpinBoxItemList.java, src/main/java/spinbox/lists/SpinBoxList.java, src/main/java/spinbox/lists/TaskList.java, src/test/java/FileTest.java, src/test/java/GradedComponentTest.java, src/test/java/ModuleTest.java, src/test/java/ReminderCommandTest.java, src/test/java/StorageTest.java
=> Implement hierarchy-based storage

src/main/java/spinbox/Parser.java, src/main/java/spinbox/SpinBox.java, src/main/java/spinbox/commands/AddCommand.java, src/main/java/spinbox/commands/Command.java, src/main/java/spinbox/commands/ExitCommand.java, src/main/java/spinbox/commands/ViewCommand.java, src/main/java/spinbox/containers/ModuleContainer.java, src/main/java/spinbox/entities/Module.java, src/test/java/ModuleTest.java, src/test/java/NotepadTest.java
To facilitate testing of other commands which depend on modules to be added properly.
=> Add minimal support for module addition

src/main/java/spinbox/commands/AddCommand.java, src/main/java/spinbox/commands/RemoveCommand.java, src/main/java/spinbox/commands/ViewCommand.java, src/main/java/spinbox/entities/Notepad.java
Partially implements: #41 
Still requires update line command before issue can be closed.
=> Notepad commands

src/main/java/spinbox/commands/AddCommand.java, src/main/java/spinbox/commands/ViewCommand.java
Implement the task commands into AddCommand.java, mark/remove task commands not implemented in this version yet.
=> Add Task Commands into Add Command

src/main/java/spinbox/Parser.java, src/main/java/spinbox/commands/AddCommand.java, src/main/java/spinbox/commands/MarkCommand.java, src/main/java/spinbox/commands/MultipleCommand.java, src/main/java/spinbox/commands/RemoveCommand.java
1. Added remove-multiple command.
2. Added mark command for tasks.
2. Fixed bug for when remove, mark and remove-multiple command have no index.
=> Implement remove-multiple command, mark command for tasks and fix bugs

src/main/java/spinbox/containers/ModuleContainer.java, src/main/java/spinbox/containers/lists/FileList.java, src/main/java/spinbox/containers/lists/GradeList.java, src/main/java/spinbox/containers/lists/SpinBoxList.java, src/main/java/spinbox/containers/lists/TaskList.java
=> Fix duplication bug

src/main/java/spinbox/Parser.java, src/main/java/spinbox/commands/AddCommand.java, src/main/java/spinbox/commands/HelpCommand.java, src/main/java/spinbox/containers/lists/HelpList.java
1. Implemented Help Command for existing commands except for grade command (marked as TBC).
Progress made on issue: #110
=> Implement Help Command

src/main/java/spinbox/Parser.java, src/main/java/spinbox/commands/AddCommand.java, src/main/java/spinbox/commands/HelpCommand.java, src/main/java/spinbox/commands/MultipleCommand.java, src/main/java/spinbox/commands/RemoveCommand.java, src/main/java/spinbox/commands/UpdateCommand.java, src/main/java/spinbox/containers/lists/HelpList.java, src/main/java/spinbox/containers/lists/TaskList.java, src/main/java/spinbox/entities/items/tasks/Event.java, src/main/java/spinbox/entities/items/tasks/Exam.java, src/main/java/spinbox/entities/items/tasks/Lab.java, src/main/java/spinbox/entities/items/tasks/Lecture.java, src/main/java/spinbox/entities/items/tasks/Tutorial.java
1. Implement the different event type tasks (e.g. exam, lab etc.)
2. Added exception for when an unknown command is added with a slash (e.g. random / )
3. Refactored a few output strings into static final form
Progress made on issue: #117
=> Implement different event type tasks and fix bug

src/main/java/spinbox/Parser.java, src/main/java/spinbox/commands/HelpCommand.java, src/main/java/spinbox/commands/RemoveMultipleCommand.java, src/main/java/spinbox/commands/SetNameCommand.java, src/main/java/spinbox/commands/SetTentativeCommand.java, src/main/java/spinbox/commands/UpdateCommand.java, src/main/java/spinbox/commands/UpdateMultipleCommand.java, src/main/java/spinbox/containers/lists/HelpList.java, src/main/java/spinbox/entities/Notepad.java
1. Implement set-name command to edit the name of a given task/note/file component. 
2. Updated helplist to reflect the addition of set-name command.
Progress made on issue: #125 #126
=> Implement SetName Command

build.gradle, src/main/java/spinbox/commands/AddCommand.java, src/main/java/spinbox/commands/Command.java, src/main/java/spinbox/commands/ExitCommand.java, src/main/java/spinbox/commands/FindCommand.java, src/main/java/spinbox/commands/FindFreeCommand.java, src/main/java/spinbox/commands/ListCommand.java, src/main/java/spinbox/commands/ReminderCommand.java, src/main/java/spinbox/commands/RemoveCommand.java, src/main/java/spinbox/commands/RemoveMultipleCommand.java, src/main/java/spinbox/commands/SetNameCommand.java, src/main/java/spinbox/commands/SetTentativeCommand.java, src/main/java/spinbox/commands/SnoozeCommand.java, src/main/java/spinbox/commands/UnknownCommand.java, src/main/java/spinbox/commands/ViewScheduleCommand.java, src/main/java/spinbox/containers/ModuleContainer.java, src/main/java/spinbox/containers/Notepad.java, src/main/java/spinbox/containers/lists/FileList.java, src/main/java/spinbox/containers/lists/GradeList.java, src/main/java/spinbox/containers/lists/SpinBoxList.java, src/main/java/spinbox/containers/lists/TaskList.java, src/main/java/spinbox/entities/Module.java, src/main/java/spinbox/entities/Notepad.java, src/main/java/spinbox/storage/StorableEntity.java, src/main/java/spinbox/storage/Storage.java, src/main/java/spinbox/storage/StorageContainer.java, src/test/java/NotepadTest.java, src/test/java/StorageTest.java
Closes #134 
Also changed build.gradle to reflect latest release.
=> Implement interface for containers w/ Storage

src/main/java/spinbox/Parser.java, src/main/java/spinbox/commands/ExportCommand.java, src/main/java/spinbox/commands/HelpCommand.java, src/main/java/spinbox/containers/lists/HelpList.java, src/main/java/spinbox/entities/items/Item.java, src/main/java/spinbox/exporter/Exportable.java, src/main/java/spinbox/exporter/Exporter.java, src/main/java/spinbox/storage/Storable.java
Closes #56, closes #40, progress on #55 and #59
=> Implement export to text framework

src/main/java/spinbox/gui/MainWindow.java
Fix implementation bug in Gui for the update of tasks. A completed task will now remain in the task list, instead of being removed. 
Closes Issue #174
=> Fix Task Update in Gui

build.gradle, src/main/java/spinbox/commands/ViewCommand.java, src/main/java/spinbox/gui/MainWindow.java
=> Add line numbers and header to notes

tutorials/javaFxTutorialPart1.md
Update javaFxTutorialPart1.md to support cross-platform JARs.
Closes issue #148
=> Implement support cross-platform JARs

src/test/java/integration/TaskCommandsIntegrationTest.java
Add integration tests to test out commands such as set-date and set-name. 
Progress made on issue: #184
=> Command integration test

src/test/java/integration/FileListIntegrationTest.java, src/test/java/integration/NotepadIntegrationTest.java, src/test/java/integration/TaskCommandsIntegrationTest.java, src/test/java/unit/ParserTest.java, src/test/java/unit/TaskTest.java
1. Modified Parser Test to test exception
2. Created Unit Test for Tasks
3. Add on more Integration tests for task
=> Modify Parser Test and Create Task Tests

src/main/java/spinbox/commands/RemoveCommand.java, src/main/java/spinbox/containers/ModuleContainer.java, src/main/java/spinbox/containers/lists/HelpList.java, src/test/java/integration/ModuleIntegrationTest.java
Modules can now be removed from the module list along with its files, provided the module is existent. 
Closes issues: #47, #157,  #163, #169
=> Implement Remove Modules Command

src/main/java/spinbox/gui/MainWindow.java, src/main/java/spinbox/gui/boxes/FileBox.java, src/main/java/spinbox/gui/boxes/GradedComponentBox.java
Users can refer to the index in the files or grades view when removing or update a component in the respective pages.
Closes issue: #153
=> Update GUI to include index for files and grades view

src/main/Resources/view/MainWindow.css, src/main/Resources/view/MainWindow.fxml, src/main/java/spinbox/commands/ViewCommand.java, src/main/java/spinbox/gui/MainWindow.java, src/test/java/integration/ParserViewCommandIntegrationTest.java
=> Fix GUI bugs and update tests

src/main/java/spinbox/commands/ExportCommand.java, src/main/java/spinbox/commands/HelpCommand.java, src/main/java/spinbox/containers/lists/HelpList.java, src/main/java/spinbox/containers/lists/TaskList.java, src/main/java/spinbox/entities/items/tasks/Schedulable.java
=> Implement export all deadlines

build.gradle, src/main/Resources/view/MainWindow.css, src/main/Resources/view/MainWindow.fxml, src/main/java/spinbox/Main.java, src/main/java/spinbox/gui/MainWindow.java
- Reworked application default size and made popup dynamic to user's screen size.
- Changed jar file version to 1.4 in anticipation of upcoming release.
- Set application title on title bar.
Closes #150, completes #146
=> Fix popup blocking input box

src/main/java/spinbox/commands/SetDateCommand.java, src/main/java/spinbox/entities/items/tasks/Event.java, src/main/java/spinbox/entities/items/tasks/Exam.java, src/main/java/spinbox/entities/items/tasks/Lab.java, src/main/java/spinbox/entities/items/tasks/Lecture.java, src/main/java/spinbox/entities/items/tasks/Schedulable.java, src/main/java/spinbox/entities/items/tasks/Tutorial.java, src/main/java/spinbox/exceptions/ScheduleDateException.java, src/test/java/integration/TaskCommandsIntegrationTest.java, src/test/java/unit/CalendarTest.java, src/test/java/unit/TaskTest.java, src/test/java/unit/ViewScheduleTest.java
Add checkValidEndDate method for Schedulable.
Update Schedulable children constructor to check if end date is valid.
Update SetDateCommand to ensure SetDate do not remove task if command
fails.
Update tests with invalid end dates.
Closes #165
=> Add Exception for Schedulable

src/main/java/spinbox/Parser.java, src/main/java/spinbox/commands/AddCommand.java, src/main/java/spinbox/commands/Command.java, src/main/java/spinbox/commands/HelpCommand.java, src/main/java/spinbox/commands/PopulateCommand.java, src/main/java/spinbox/commands/RemoveCommand.java, src/main/java/spinbox/commands/RemoveMultipleCommand.java, src/main/java/spinbox/commands/ScoreCommand.java, src/main/java/spinbox/commands/SetDateCommand.java, src/main/java/spinbox/commands/SetNameCommand.java, src/main/java/spinbox/commands/UpdateCommand.java, src/main/java/spinbox/commands/UpdateMultipleCommand.java, src/main/java/spinbox/containers/lists/HelpList.java, src/main/java/spinbox/gui/MainWindow.java
=> Add command to populate sample data

src/main/Resources/view/MainWindow.fxml, src/main/Resources/view/itemBoxes/TaskBox.fxml, src/main/java/spinbox/containers/lists/TaskList.java, src/main/java/spinbox/entities/Calendar.java, src/main/java/spinbox/gui/MainWindow.java
Add ExamView to MainView
Filter out Exams from Urgent Task
Resize TaskBox
Add header to MainView
Closes #48
=> Add ExamView to Main

build.gradle
Edit build.gradle to implement cross-platform support for SpinBox.
=> Implement Cross Platform Support for SpinBox

src/main/java/spinbox/entities/items/tasks/Deadline.java, src/main/java/spinbox/entities/items/tasks/Event.java, src/main/java/spinbox/entities/items/tasks/Exam.java, src/main/java/spinbox/entities/items/tasks/Lab.java, src/main/java/spinbox/entities/items/tasks/Lecture.java, src/main/java/spinbox/entities/items/tasks/Schedulable.java, src/main/java/spinbox/entities/items/tasks/Tutorial.java, src/test/java/integration/TaskCommandsIntegrationTest.java, src/test/java/unit/CalendarTest.java, src/test/java/unit/TaskTest.java, src/test/java/unit/ViewScheduleTest.java
Add Exception Handling for Scheulable Tasks.
Schedulable Tasks are now unable to add something with start date in the
past.
Closes #151
=> Add Exception Handling

src/main/java/spinbox/commands/RemoveMultipleCommand.java, src/main/java/spinbox/commands/UpdateMultipleCommand.java, src/test/java/integration/FileListIntegrationTest.java, src/test/java/integration/ModuleIntegrationTest.java, src/test/java/integration/NotepadIntegrationTest.java, src/test/java/integration/ParserViewCommandIntegrationTest.java, src/test/java/integration/TaskCommandsIntegrationTest.java
1. Change the test module names and add remove module command at the end of every integration test
2. Add new integration tests
=> Edit Test Module Name and Add Integration Tests

src/main/java/spinbox/Main.java, src/main/java/spinbox/Parser.java, src/main/java/spinbox/SpinBox.java, src/main/java/spinbox/entities/items/GradedComponent.java, src/main/java/spinbox/exporter/Exporter.java, src/main/java/spinbox/gui/MainWindow.java, src/main/java/spinbox/storage/Storage.java
Exports to a log file within SpinBoxData
=> Incorporate logging

src/main/java/spinbox/Parser.java
Refactor Parser to adhere to the good code quality standard.
=> Refactor Parser

src/main/java/spinbox/gui/MainWindow.java
Added a "to" between the start and end date time of a schedulable task.
=> Update GUI for Main Page

src/main/Resources/view/CalendarMonthBox.fxml, src/main/Resources/view/MainWindow.fxml, src/main/java/spinbox/commands/ViewCommand.java, src/main/java/spinbox/containers/lists/HelpList.java, src/main/java/spinbox/entities/Calendar.java, src/main/java/spinbox/gui/CalendarMonthBox.java, src/main/java/spinbox/gui/MainWindow.java
Add selection function for calendar view command.
Add scrolling functionality for large amounts of task in a single day for Calendar GUI.
GUI slight resizing.
=> Improve Calendar GUI and view command
